### PR TITLE
remove healthcheck - closes #683

### LINKED ISSUE #683: Fix broken healthcheck
Healthcheck "Change Sets" and "Latest Deployed Commit" are broken now because Unity isn't deployed with Jenkins anymore.

### PR DESCRIPTION
**Pull request by gvn**
Digging into Heroku further I've determined that it's going to be fairly difficult to recreate our old healthcheck that was using the Jenkins API.

All the info we had in the healthcheck is available through Heroku, so I'm just going to remove it...

### CODE REVIEW

File: scripts/build-healthcheck.js [hunk 1]
```diff
@@ -1,82 +0,0 @@
...
-//       V| \                 / |V
-//        | |T~\___!___!___/~T| |
-//        | |`IIII_I_I_I_IIII'| |
-//        |  \,III I I I III,/  |
-//         \   `~~~~~~~~~~'    /
-//           \   .       .   /
-//             \.    ^    ./
-//               ^~~~^~~~^
-//
-//     NEVER EMIT PRIVATE KEYS OR OTHER SENSITIVE DATA!
```
Comment (mmmavis) [inline scripts/build-healthcheck.js]: 💀
