### PR TITLE
Moving partnership logo to featured card bio

### LINKED ISSUE #225: Fix layout on featured profiles
Currently, if a featured profile has a short quote and long list under more details, the layout of the quote looks broken ... card preserve the height of the hidden details.

### PR DESCRIPTION
**Pull request by alanmoo**
Closes #225

### CODE REVIEW

File: source/js/components/people/person.jsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ export default class Person extends React.Component {
     }
 
     let socialLinks = Object.keys(filteredLinks).map((linkKey, index) => {
-      let classes = linkKey + ` mr-3`;
+      let classes = linkKey + ` mr-4`;
```
Comment (gvn) [inline source/js/components/people/person.jsx]: You shouldn't need to concatenate strings like this anymore:

Use this instead: `${linkKey} mr-4`
